### ISSUE TITLE
大佬这个能适配小程序么？

### ISSUE THREAD

**Issue by NLcoin** [deepsearun/uniapp-alonebook#1]
这个是安卓的吧？后端需要安装狂雨么？能适配下小程序么？

**Comment by deepsearun** [comment]
um，小程序还没试过，阅读页面肯定要重写，其他页面 你可以去小程序试试，应该是没啥大问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deepsearun/uniapp-alonebook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 中午12:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[deepsearun/uniapp-alonebook] 大佬这个能适配小程序么？ (#1)





 
这个是安卓的吧？后端需要安装狂雨么？能适配下小程序么？

**Comment by NLcoin** [comment]
小程序编译不行，错误不少，还有最近发现一款小说也是狂雨后端，但他是前端采集，而且能采集到后端不能采集的收费内容。

**Comment by NLcoin** [comment]
小程序编译不行，错误不少，还有最近发现一款小说也是狂雨后端，但他是前端采集，而且能采集到后端不能采集的收费内容。
